#!/bin/bash
#
set +e
#
if [ ${EUID} -ne 0 ]; then
    echo "CreateUsers: Unable to create users, must run as root"
    exit 99
fi
#
echo "CreateUsers: MQ Users "
echo "----------------------"
#
createUser() {
    local u1=$1
    local p1=$2
    if [ `sed -n "/^${u1}/p" /etc/passwd` ]; then
        echo "User [${u1}] already exists"
    else
        echo "User [${u1}] doesn't exist ... creating"
        if [ -e ${p1} ]; then
            p1=`date +%s | sha256sum | base64 | head -c 16 ; echo`
        fi
        echo "User: ${u1}, ${p1} added"
        useradd -G mqm ${u1}
        echo ${u1}:${p1} | chpasswd
    fi    
}
#
. /opt/mqm/bin/setmqenv -s
dspmqver
#
echo "CreateUsers: Creating users ..."
#createUser mqdocker
#createUser mquser01 Passw0rd
#createUser mquser02 Passw0rd
#
# Create users
#
inputdir=~/scripts/mqscripts
inputfile=${inputdir}/users
if [ -f inputfile ]; then
    echo "CreateUsers: user file is missing, no users will be created"
    exit 99
fi
echo "CreateUsers: input file used - ${inputfile}"
#
# Read the users line-by-line, delimited by comma
#
while IFS=, read -r userid password
do
    if [ ! -f ${password} ]; then
        #echo "userid  : ${userid}"
        #echo "password: ${password}"
        createUser ${userid} ${password} 
    fi
done < ${inputfile}
#
set -e
